# Docker 容器数据备份工具配置文件

backup_mapping_path = "./backup_mapping.toml"

# 备份文件的默认输出目录
backup_dir = "./backups"

# Docker 相关配置
[docker]
# Docker daemon 的地址
host = "unix:///var/run/docker.sock"
# 是否使用 TLS
tls = false
# 证书路径 (如果使用 TLS)
# cert_path = "/path/to/cert"
