# Docker 容器数据备份工具配置文件

    # 备份文件的默认输出目录
    # backup_dir = "./backups"

    # 停止容器操作的超时时间 (单位：秒)
    # timeout = 30

    # 备份映射文件路径
    # [mapper]
    # mapping_path = "./backups/mapping.toml"

    # Docker 相关配置
    # [docker]
    # Docker daemon 的地址
    # host = "unix:///var/run/docker.sock"
    # 是否使用 TLS
    # tls = false
    # 证书路径 (如果使用 TLS)
    # cert_path = "/path/to/cert"
backup_dir = "./backups"
timeout = 30

[mapper]
mapping_path = "./backups/mapping.toml"

[docker]
host = "unix:///var/run/docker.sock"
tls = false
