services:
  sim-server:
    build: .
    container_name: sim-server
    ports:
      - "8666:8666"
    volumes:
      - /home/unic/downloads/testd/py/data:/app/data
      - /home/unic/downloads/testd/py/config:/app/config
    restart: unless-stopped
    # Resource limits - 移除 memory 相关限制以避免 swap 警告
    deploy:
      resources:
        limits:
          cpus: '0.50'
        reservations:
          cpus: '0.25'
    # Logging configuration  
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    # Health check
    healthcheck:
      test: [ "CMD", "curl", "http://localhost:8666/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    # healthcheck:
    #   test: [ "CMD", "wget", "--spider", "-q", "http://localhost:8666" ]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3
    #   start_period: 5s
